name: RunTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd ~
        curl -s https://get.nextflow.io | bash
        chmod +x nextflow
        curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - ~/
        cd $GITHUB_WORKSPACE
        ~/nextflow -version
        ~/apptainer --version
        pwd
